### ISSUE TITLE
具体时间对不上，请问如何解决

### ISSUE THREAD

**Issue by Damiey** [pfeak/docsify-updated#1]
具体时间对不上，请问如何解决

**Comment by pfeak** [comment]
> 具体时间对不上，请问如何解决

可以给详细的描述吗？文件是否在不同的操作系统上移动过？

**Comment by Damiey** [comment]
没有。我用的是CentOS宝塔，上方修改日期确实对应北京时间

**Comment by Damiey** [comment]
我将文件删除重新创建就可以了，麻烦您了

**Comment by pfeak** [comment]
> 我将文件删除重新创建就可以了，麻烦您了

好的，不用客气。

**Comment by Damiey** [comment]
> > 我将文件删除重新创建就可以了，麻烦您了
> 
> 好的，不用客气。

请问你知道怎么让支持引用 > 的更新日期用<center></center>居中显示吗

**Comment by pfeak** [comment]
将插件配置中 '&gt;' 去掉，然后嵌套一个 div 标签，例如 <div align='center'&gt;最后更新时间: {docsify-updated}</div&gt;，css 样式同理。我将会把这一点更新到 README.md 中。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月14日(星期五) 晚上8:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [pfeak/docsify-updated] 具体时间对不上，请问如何解决 (Issue #1)





   
我将文件删除重新创建就可以了，麻烦您了
  
好的，不用客气。
  
请问你知道怎么让支持引用 &gt; 的更新日期用
居中显示吗

 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
