### ISSUE TITLE
[Feature Request] Would it possible to place the time-updated section above?

### ISSUE THREAD

**Issue by Maxlinn** [pfeak/docsify-updated#2]
Hi there, thanks for bringing this plugin, it worked as a charm, credits to your work.

Nevertheless, would it possible to place the time-updated section to the top of the page? Or add a switch `whereToPlace: 'top'/'bottom'`. In my usecase, some pages are updated so often that i have the habit to check the update time, but scrolling to every bottom is not so convenient.

I would like to fix it myself and send you a PR, but i'm not familiar with frontend. Is it possible to bring out this feature?

Thanks in advance.

**Comment by pfeak** [comment]
> 

Thank you for using and giving valuable suggestions, I will add this feature as soon as possible, probably tomorrow.

**Comment by Maxlinn** [comment]
Thank you for your instant reply and efforts, best wishes!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月9日(星期六) 晚上11:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [pfeak/docsify-updated] [Feature Request] Would it possible to place the time-updated section above? (Issue #2)





   
Thank you for using and giving valuable suggestions, I will add this feature as soon as possible, probably tomorrow.

**Comment by pfeak** [comment]
Now you can set the position of the label via `whereToPlace`.

```javascript
window.$docsify = {
timeUpdater: {
    text: ">last update time: {docsify-updated}",
    formatUpdated: "{YYYY}/{MM}/{DD}",
    whereToPlace: "top",  // "top" or "bottom", default to "bottom"
  },
};```

**Comment by Maxlinn** [comment]
Thank you for that, it worked out fine!
