### ISSUE TITLE
变量名与 Docsify Count 冲突

### ISSUE THREAD

**Issue by xueelf** [pfeak/docsify-updated#3]
插件 [count](https://github.com/827652549/docsify-count) 也使用到了 defaultOptions 这个变量从而导致 js 报错，有没有好一点的解决办法 orz

**Comment by pfeak** [comment]
已经在 [1.0.5](https://www.npmjs.com/package/docsify-updated/v/1.0.5) 版本解决了这个问题，但 jsdelivr 等待最新版本代码刷新可能需要一定时间，如果想要快速看到效果，可以通过访问一次 jsdelivr 网页手动刷新本地访问 jsdelivr 资源，刷新命令如下：
`https://cdn.jsdelivr.net/npm/docsify-updated/src/time-updater.min.js`
然后清空浏览器缓存，刷新网页即可看到效果。

**Comment by xueelf** [comment]
> 已经在 [1.0.5](https://www.npmjs.com/package/docsify-updated/v/1.0.5) 版本解决了这个问题，但 jsdelivr 等待最新版本代码刷新可能需要一定时间，如果想要快速看到效果，可以通过访问一次 jsdelivr 网页手动刷新本地访问 jsdelivr 资源，刷新命令如下： `https://cdn.jsdelivr.net/npm/docsify-updated/src/time-updater.min.js` 然后清空浏览器缓存，刷新网页即可看到效果。

蟹蟹 QwQ
