### ISSUE TITLE
The “last update time of this doc”  is not accurate

### ISSUE THREAD

**Issue by seeflood** [pfeak/docsify-updated#5]
Thanks for your great tool.
We found that “last update time of this doc”  is often changed, even if the doc is not updated
For more details, see  https://github.com/mosn/layotto/issues/615
![image](https://user-images.githubusercontent.com/26001097/170829732-f51e38a5-ceaa-44b7-8e6a-8d954d49cc6d.png)

**Comment by pfeak** [comment]
The plugin will get the file update time on the system.
**When CI documents from github or gitlab, the file time on the system will change and become the time of CI** (this is why the plugin shows the time inaccurate).

The idea is to use `git` to repair the file time during the CI process. The command is as follows:
`git ls-files | while read file; do touch -d $(git log -1 --format="@%ct" "$file") "$file"; done`

**Comment by pfeak** [comment]
Same goes for CD or manual deployment.

**Comment by seeflood** [comment]
Thanks for your explanation ! Now I know why.
>The idea is to use git to repair the file time during the CI process. The command is as follows:
git ls-files | while read file; do touch -d $(git log -1 --format="@%ct" "$file") "$file"; done

But I don't know where to add this command in github workflow 😢 
As far as I know, the github workflow starts a new container for every job . So even if I modify the timestamp in a job , the container will be destroyed after the job finished, and nothing will be changed.
![image](https://user-images.githubusercontent.com/26001097/170848893-504081f4-24d0-491b-80e8-d5d4d1ce8ac6.png)


I also found a github-action https://github.com/chetan/git-restore-mtime-action . It's used before building the doc site, but docsify doesn't have a "build" step

**Comment by pfeak** [comment]
It is recommended to use `git` to fix file update times during deployment of docsify documentation (continuous or manual).

For example to manually deploy the document:
```shell
# clone repo
git clone https://github.com/mosn/layotto.git

# cd dir
cd layotto

# repair file update time
git ls-files | while read file; do touch -d $(git log -1 --format="@%ct" "$file") "$file"; done

# Start the docsify service
docsify serve docs/
```
